from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Any

from config import GEMINI_API_KEY, MODEL_NAME
from openai import OpenAI
from scenarios import preset_choices, resolve_scenario

_ROOT = Path(__file__).resolve().parent.parent
_PROMPTS_DIR = _ROOT / "prompts"


def _gemini_client() -> OpenAI:
    if not GEMINI_API_KEY:
        raise ValueError("GEMINI_API_KEY is not set (used as GEMINI_API_KEY in config.py)")
    return OpenAI(
        api_key=GEMINI_API_KEY,
        base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
    )


def load_prompt(filename: str) -> str:
    path = _PROMPTS_DIR / filename
    if not path.exists():
        raise FileNotFoundError(f"Prompt file not found: {path}")
    return path.read_text(encoding="utf-8").strip()


def build_judge_system_prompt() -> str:
    return load_prompt("judge_prompt.md")


def build_improve_system_prompt() -> str:
    improve = load_prompt("improve_prompt.md")
    # Keep the existing prompt as the source of truth, but make explicit that the
    # input includes an evaluation generated by a separate judge call.
    return (
        f"{improve}\n\n"
        "You will be given a 'Judge evaluation' section written by a separate evaluator. "
        "Use it as the primary basis for your coaching (cite its scores/snippets), and "
        "use the scenario/transcript/features only to ground rewrites and practice steps.\n"
    )


def select_context() -> str:
    choices = preset_choices()
    print("\nSelect your conversation context:")
    for i, key in enumerate(choices, 1):
        print(f"  {i}. {key}")
    choice = input("\nEnter number: ").strip()
    try:
        key = choices[int(choice) - 1]
    except (ValueError, IndexError):
        key = choices[0]
    _, scenario_text = resolve_scenario(key, None)
    return scenario_text


def build_turn_payload(
    transcript: str,
    context: str,
    analysis: dict[str, Any],
    turn: int,
) -> str:
    analysis_str = json.dumps(analysis, indent=2, ensure_ascii=False)
    return f"""## Scenario
{context}

## Transcript (turn {turn})
{transcript}

## Delivery features
```json
{analysis_str}
```
"""


def judge_evaluation(
    transcript: str,
    context: str,
    analysis: dict[str, Any],
    *,
    turn: int,
    model: str,
) -> str:
    client = _gemini_client()
    messages: list[dict[str, Any]] = [
        {"role": "system", "content": build_judge_system_prompt()},
        {"role": "user", "content": build_turn_payload(transcript, context, analysis, turn)},
    ]
    r = client.chat.completions.create(model=model, messages=messages)
    return (r.choices[0].message.content or "").strip()


def improvement_coaching(
    transcript: str,
    context: str,
    analysis: dict[str, Any],
    *,
    turn: int,
    model: str,
    judge_text: str,
    stream: bool = False,
) -> str:
    client = _gemini_client()
    user_message = (
        f"{build_turn_payload(transcript, context, analysis, turn)}\n"
        "## Judge evaluation\n"
        f"{judge_text}\n"
    )
    messages: list[dict[str, Any]] = [
        {"role": "system", "content": build_improve_system_prompt()},
        {"role": "user", "content": user_message},
    ]

    if not stream:
        r = client.chat.completions.create(model=model, messages=messages)
        return (r.choices[0].message.content or "").strip()

    parts: list[str] = []
    s = client.chat.completions.create(model=model, messages=messages, stream=True)
    for chunk in s:
        if not chunk.choices:
            continue
        delta = chunk.choices[0].delta
        if delta is None:
            continue
        piece = getattr(delta, "content", None) or ""
        if piece:
            parts.append(piece)
            print(piece, end="", flush=True)
    print(flush=True)
    return "".join(parts).strip()


def save_two_stage_feedback(
    *,
    context: str,
    transcript: str,
    analysis: dict[str, Any],
    turn: int,
    judge_text: str,
    improvement_text: str,
    output_path: str,
) -> list[dict[str, Any]]:
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    if out.exists():
        history = json.loads(out.read_text(encoding="utf-8"))
    else:
        history = []

    history.append(
        {
            "turn": turn,
            "timestamp": datetime.now().isoformat(),
            "context": context,
            "transcript": transcript,
            "analysis": analysis,
            "judge_evaluation": judge_text,
            "improvement": improvement_text,
            "feedback": f"{judge_text}\n\n---\n\n{improvement_text}",
        }
    )
    out.write_text(json.dumps(history, indent=2, ensure_ascii=False), encoding="utf-8")
    return history


def load_last_turn(output_path: str) -> int:
    path = Path(output_path)
    if not path.exists():
        return 1
    history = json.loads(path.read_text(encoding="utf-8"))
    if not history:
        return 1
    last = history[-1]
    return int(last.get("turn", 0)) + 1


def _load_transcript_json(path: Path) -> tuple[str, dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    transcript = (data.get("transcript") or "").strip()
    if not transcript:
        raise ValueError(f"Missing/empty transcript in: {path}")
    analysis = data.get("analysis") or {}
    if not isinstance(analysis, dict):
        analysis = {}
    return transcript, analysis


def main() -> int:
    parser = argparse.ArgumentParser(
        description="DialogCoach feedback agent (Gemini backend, two-stage: judge -> improve).",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--model", default=MODEL_NAME, help="Gemini model id.")
    parser.add_argument(
        "--stream-improve",
        action="store_true",
        help="Stream tokens while generating the improvement stage.",
    )
    parser.add_argument(
        "--output",
        default="recordings/feedback.json",
        help="Feedback history JSON path.",
    )
    args = parser.parse_args()

    context = select_context()
    turn = load_last_turn(args.output)
    transcript, analysis = _load_transcript_json(Path(f"recordings/transcript_turn{turn}.json"))

    print("\nGenerating judge evaluation...\n", flush=True)
    print(f"  Gemini model (judge): {args.model}", flush=True)
    judge_text = judge_evaluation(
        transcript,
        context,
        analysis,
        turn=turn,
        model=args.model,
    )

    print("\n--- Judge evaluation ---\n")
    print(judge_text)

    print("\nGenerating improvement coaching...\n", flush=True)
    print(f"  Gemini model (improve): {args.model}", flush=True)
    improvement_text = improvement_coaching(
        transcript,
        context,
        analysis,
        turn=turn,
        model=args.model,
        judge_text=judge_text,
        stream=args.stream_improve,
    )

    save_two_stage_feedback(
        context=context,
        transcript=transcript,
        analysis=analysis,
        turn=turn,
        judge_text=judge_text,
        improvement_text=improvement_text,
        output_path=args.output,
    )

    if not args.stream_improve:
        print("\n--- Improvement coaching ---\n")
        print(improvement_text)
    print(f"\nFeedback saved. (Turn {turn} complete)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

